### ISSUE TITLE
Test failing - test_import_export and test_import_prediction

### ISSUE THREAD

**Issue by laurentdavid** [moodlehq/moodle-mlbackend-python#54]
It seems that test are failing on those two

`python -mpytest`

Result:

```
====================================================================== short test summary info =======================================================================
FAILED test/test_local.py::test_import_export - assert 1 == 0
FAILED test/test_local.py::test_import_prediction - assert 1 == 0
================================================== 2 failed, 34 passed, 1 xfailed, 22 warnings in 189.77s (0:03:09) ==================================================
```

From a very quick check, I could see that the exception is generated through _reconstruct_model and the fact that self._proto.nodes[model_id].user_object.metadata is empty. But I might be wrong.

**Comment by douglasbagnall** [comment]
Could you post the output of `python3 -mpytest -s -v -v -k 'import_export or import_pred'`?

**Comment by laurentdavid** [comment]
Hi @douglasbagnall,

Thanks for your quick answer.

Here it is: [test_import_export.txt](https://github.com/moodlehq/moodle-mlbackend-python/files/8639517/test_import_export.txt)

It might be a bad setup from my end, but I cannot see what I have done wrong.

Laurent

**Comment by douglasbagnall** [comment]
Thanks. I can't see what is wrong either.

the underlying traceback is:
```
Traceback (most recent call last):
  File "/home/laurentd/.pythonz/pythons/CPython-3.7.13/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/laurentd/.pythonz/pythons/CPython-3.7.13/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/laurentd/development/moodle-mlbackend-python/moodlemlbackend/import.py", line 24, in <module>
    import_classifier()
  File "/home/laurentd/development/moodle-mlbackend-python/moodlemlbackend/import.py", line 17, in import_classifier
    classifier.import_classifier(sys.argv[3])
  File "/home/laurentd/development/moodle-mlbackend-python/moodlemlbackend/processor/estimator.py", line 622, in import_classifier
    classifier = self.load_classifier(importdir)
  File "/home/laurentd/development/moodle-mlbackend-python/moodlemlbackend/processor/estimator.py", line 596, in load_classifier
    classifier = super(Classifier, self).load_classifier(model_dir)
  File "/home/laurentd/development/moodle-mlbackend-python/moodlemlbackend/processor/estimator.py", line 121, in load_classifier
    classifier.load(path)
  File "/home/laurentd/development/moodle-mlbackend-python/moodlemlbackend/model/tensor.py", line 87, in load
    self.model = tf.keras.models.load_model(path)
  File "/home/laurentd/.local/share/virtualenvs/moodleanalytics/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/home/laurentd/.local/share/virtualenvs/moodleanalytics/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 155, in load
    keras_loader.finalize_objects()
  File "/home/laurentd/.local/share/virtualenvs/moodleanalytics/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 626, in finalize_objects
    self._reconstruct_all_models()
  File "/home/laurentd/.local/share/virtualenvs/moodleanalytics/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 645, in _reconstruct_all_models
    self._reconstruct_model(model_id, model, layers)
  File "/home/laurentd/.local/share/virtualenvs/moodleanalytics/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 662, in _reconstruct_model
    self._proto.nodes[model_id].user_object.metadata)['config']
  File "/home/laurentd/.local/share/virtualenvs/moodleanalytics/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 62, in decode
    return json.loads(json_string, object_hook=_decode_helper)
  File "/home/laurentd/.pythonz/pythons/CPython-3.7.13/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/home/laurentd/.pythonz/pythons/CPython-3.7.13/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/laurentd/.pythonz/pythons/CPython-3.7.13/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
where the test is effectively trying to run

```
python3 -m moodlemlbackend.import temp_id_and_dir-1651835261-zdDnKC4E /home/laurentd/development/moodle-mlbackend-python/test/temp-data/temp_id_and_dir-1651835261-zdDnKC4E /home/laurentd/development/moodle-mlbackend-python/test/test-models/split-evaluation
```

So by the time it gets to here:
```
  File "/home/laurentd/development/moodle-mlbackend-python/moodlemlbackend/import.py", line 17, in import_classifier
    classifier.import_classifier(sys.argv[3])
```
the `sys.argv[3]` mentioned should be `/home/laurentd/development/moodle-mlbackend-python/test/test-models/split-evaluation`

and this string soon gets passed to `tensorflow.keras.models.load_model()`.

That path must exist (or we'd see a quicker failure), but tensorflow thinks the model is missing some embedded JSON string (`self._proto.nodes[model_id].user_object.metadata)['config']` is some clue).

It seems unlikely that you'd have corrupt files under `test/test-models/split-evaluation` (you could check with `git status`), so I'm suspecting tensorflow version unhappiness.

**Comment by douglasbagnall** [comment]
The CI used  python 3.7, tensorflow-2.7.1

https://github.com/moodlehq/moodle-mlbackend-python/pull/51/checks

**Comment by laurentdavid** [comment]
Hi @douglasbagnall 

Thanks for the pointer. I think we can close this ticket. I will upgrade tensorflow to 2.7.1 rather than 2.5.3.

Laurent
